# <span style="color: MediumPurple;"> Lecture 12   </span>

## <span style="color: MediumPurple;"> Sophia Dalal, April 22 2025 <span>

### <span style="color: Purple;"> Import and add everything you need for today (no need todo extra stuff)! <span>

In [3]:
pip install plotly


Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas 
import numpy 
import statsmodels.api

In [6]:
pip install patsy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np 
import pandas as pd 
from scipy import stats 
from pandas import DataFrame


In [6]:
import plotly.graph_objects as go
import plotly.express as px 
import plotly.figure_factory as ff
import plotly.io as pio
pio.templates.default = "plotly_white"

In [7]:
import statsmodels.api as sm 
from patsy import dmatrices

### <span style="color: MediumPurple;"> Correlation - Numerical <span>

### <span style="color: MediumPurple;"> Associated - Categorical <span>

In [12]:
# Seed the numpy pseudo-random number generator with the integer 7
np.random.seed(7) # For reproducible results

# Generate two numpy arrays
independent = np.round(np.random.uniform(low=80, high=100, size=50), 1)
dependent = np.round(independent + np.random.normal(0, 5, 50), 1)

In [15]:
# Generate a scatter plot of the data
fig = go.Figure(
    go.Scatter(
        x=independent,
        y=dependent,
        mode='markers',
        marker=dict(size=12)
    )
)

fig.update_layout(
    title='Scatter plot of data',
    xaxis_title='Independent variable',
    yaxis_title='Dependent variable',
    width=700
)

fig.show()


### <span style="color: pink;"> Calculate Variance <span>

In [16]:
# Use numpy to calculate the variance using the equation for sample variance
np.sum((independent - np.mean(independent))**2) / (len(independent) - 1)

np.float64(27.3082)

In [17]:
# Calculate the sample variance of the independent variable
np.var(independent, ddof=1)

np.float64(27.3082)

In [18]:
# Determine the variance in the dependent variable
np.var(dependent, ddof=1)

np.float64(51.59557551020409)

In [19]:
# Determine the covariance matrix
np.cov(independent, dependent)

array([[27.3082    , 26.88066122],
       [26.88066122, 51.59557551]])

In [20]:
# Calculate the correlation coefficient
np.cov(independent, dependent)[0, 1] / (np.std(independent, ddof=1) * np.std(dependent, ddof=1))

np.float64(0.7161222698456383)

In [21]:
r, p = stats.pearsonr(
    independent,
    dependent
)

r # Pearson correlation coefficient

np.float64(0.7161222698456389)

In [22]:
p # p value

np.float64(5.0173395434123214e-09)

### <span style="color: pink ;">Simple Linear Regression <span>

In [24]:
go.Figure(data=go.Scatter(x=independent, y=dependent,
    mode='markers',
    marker=dict(size=12))).update_layout(title='Data',
        yaxis=dict(title='Dependent variable'),
        xaxis=dict(title='Independent variable')).update_layout(
            width=700
        )

In [25]:
# Create a pandas dataframe object to hold the data and add a new variable
df = DataFrame({'Independent':independent, 'Dependent':dependent, 'Group':np.repeat(['C', 'E'], 25)})
df[:5]

Independent  Dependent Group
0         81.5       73.0     C
1         95.6       86.6     C
2         88.8       90.7     C
3         94.5      105.7     C
4         99.6      100.9     C

In [26]:
# Formula for dependent variable given the independent variable
y, X = dmatrices('Dependent ~ Independent', data = df)

In [27]:
# The target vector
y

DesignMatrix with shape (50, 1)
  Dependent
       73.0
       86.6
       90.7
      105.7
      100.9
       88.2
       99.6
       82.6
       85.9
       91.3
       92.9
       94.6
       80.4
       83.8
       85.3
      104.2
       82.5
       79.5
       98.1
       89.0
       90.1
       94.6
       78.6
       85.7
       96.7
       76.8
       98.0
       93.6
       93.9
       96.6
  [20 rows omitted]
  Terms:
    'Dependent' (column 0)
  (to view full data, use np.asarray(this_obj))

In [28]:
# The design matrix
X

DesignMatrix with shape (50, 2)
  Intercept  Independent
          1         81.5
          1         95.6
          1         88.8
          1         94.5
          1         99.6
          1         90.8
          1         90.0
          1         81.4
          1         85.4
          1         90.0
          1         93.6
          1         96.1
          1         87.6
          1         81.3
          1         85.8
          1         98.2
          1         84.3
          1         89.0
          1         98.6
          1         80.5
          1         92.0
          1         99.0
          1         84.6
          1         91.0
          1         98.2
          1         82.7
          1         90.5
          1         95.0
          1         93.4
          1         89.4
  [20 rows omitted]
  Terms:
    'Intercept' (column 0)
    'Independent' (column 1)
  (to view full data, use np.asarray(this_obj))

In [32]:
# Make a linear regression model
model = sm.OLS(y, X).fit()
# Print the summary of the model
model.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              Dependent   R-squared:                       0.513
Model:                            OLS   Adj. R-squared:                  0.503
Method:                 Least Squares   F-statistic:                     50.53
Date:                Tue, 22 Apr 2025   Prob (F-statistic):           5.02e-09
Time:                        10:04:14   Log-Likelihood:                -151.05
No. Observations:                  50   AIC:                             306.1
Df Residuals:                      48   BIC:                             309.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       1.7253     12.503      0.138      0.891     -23.414      26.865
Independent     0.9843      0.138      7.108      0.000       0.706       1.263
==============================================================================
Omnibus:                        0.158   Durbin-Watson:                   1.583
Prob(Omnibus):                  0.924   Jarque-Bera (JB):                0.365
Skew:                           0.011   Prob(JB):                        0.833
Kurtosis:                       2.582   Cond. No.                     1.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
# Make a linear regression model on a plot. Make the fitted line red and the dots blue. 
fig = go.Figure()
fig.add_trace(go.Scatter(x=independent, y=dependent,
                         mode='markers',
                         marker=dict(size=12),
                         name='Data'))
fig.add_trace(go.Scatter(x=independent, y=model.predict(X),
                            mode='lines',
                            line=dict(color='red', width=2),
                            name='Fitted line'))
fig.update_layout(title='Linear regression model',
                    yaxis=dict(title='Dependent variable'),
                    xaxis=dict(title='Independent variable')).update_layout(
                        width=700
                    )

### <span style="color: MediumPurple;"> Ordinary Least Squares <span>

In [42]:
linear_model = sm.OLS(y, X).fit()

In [43]:
linear_model.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                 Results: Ordinary least squares
=================================================================
Model:              OLS              Adj. R-squared:     0.503   
Dependent Variable: Dependent        AIC:                306.0983
Date:               2025-04-22 10:11 BIC:                309.9223
No. Observations:   50               Log-Likelihood:     -151.05 
Df Model:           1                F-statistic:        50.53   
Df Residuals:       48               Prob (F-statistic): 5.02e-09
R-squared:          0.513            Scale:              25.659  
------------------------------------------------------------------
               Coef.   Std.Err.    t     P>|t|    [0.025    0.975]
------------------------------------------------------------------
Intercept      1.7253   12.5032  0.1380  0.8908  -23.4140  26.8646
Independent    0.9843    0.1385  7.1083  0.0000    0.7059   1.2628
-----------------------------------------------------------------
Omnibus:              0.158        Durbin-Watson:           1.583
Prob(Omnibus):        0.924        Jarque-Bera (JB):        0.365
Skew:                 0.011        Prob(JB):                0.833
Kurtosis:             2.582        Condition No.:           1576 
=================================================================
Notes:
[1] Standard Errors assume that the covariance matrix of the
errors is correctly specified.
[2] The condition number is large, 1.58e+03. This might indicate
that there are strong multicollinearity or other numerical
problems.
"""

In [44]:
# Gerating x and y values for the line
x_vals = np.arange(80, 100, 0.1)
y_vals = 1.7253 + 0.9843 * x_vals

go.Figure(data=go.Scatter(x=independent, y=dependent,
    mode='markers',
    name='Data',
    marker=dict(size=12))).update_layout(title='Best fit model',
        yaxis=dict(title='Dependent variable'),
        xaxis=dict(title='Independent variable')).add_trace(go.Scatter(
            x=x_vals, y=y_vals,
            name='Best model',
            mode='lines'
        )).update_layout(
            width=700
        )

In [45]:
# Residuals of best model
linear_model.resid

array([-8.94929966, -9.22854923,  1.56498957, 10.9542291 ,  1.134075  ,
       -2.90369831,  9.28377684,  0.74913474,  0.11175897,  0.98377684,
       -0.95986135, -1.7207212 , -7.5537977 ,  2.04756913, -0.88197861,
        5.81215652, -2.20546269, -9.83187922, -0.68158106,  8.03504428,
       -2.18491104, -4.57531863, -6.40076588, -5.6005671 , -1.68784348,
       -6.33051239,  7.19160487, -1.63794287,  0.23700744,  6.8743832 ,
        7.09140609, -1.41935437,  1.34307109,  3.37594881, -1.35849452,
       -9.10976196,  3.06831956,  4.12584942,  1.80726093, -4.98667542,
       -1.33031361, -3.36162573, -1.76768938,  6.14307109,  7.27125199,
        3.0526635 ,  2.35716154,  3.21059091, -0.51642193, -0.64107408])

In [46]:
# Model predictions given the data
linear_model.predict(X)

array([81.94929966, 95.82854923, 89.13501043, 94.7457709 , 99.765925  ,
       91.10369831, 90.31622316, 81.85086526, 85.78824103, 90.31622316,
       93.85986135, 96.3207212 , 87.9537977 , 81.75243087, 86.18197861,
       98.38784348, 84.70546269, 89.33187922, 98.78158106, 80.96495572,
       92.28491104, 99.17531863, 85.00076588, 91.3005671 , 98.38784348,
       83.13051239, 90.80839513, 95.23794287, 93.66299256, 89.7256168 ,
       84.50859391, 90.11935437, 87.75692891, 89.82405119, 87.65849452,
       97.00976196, 95.63168044, 86.67415058, 91.79273907, 85.88667542,
       89.43031361, 87.46162573, 93.36768938, 87.75692891, 89.52874801,
       94.6473365 , 88.64283846, 98.28940909, 84.01642193, 95.04107408])

In [47]:
# Sum of squared errors for the model
var_best_model = np.var(linear_model.resid)
var_best_model

np.float64(24.633044299379904)

In [50]:
var_mean_model = np.var(dependent)
var_mean_model

np.float64(50.56366400000001)

In [51]:
# R squared
(var_mean_model - var_best_model) / var_mean_model


np.float64(0.5128311053688692)

### <span style="color: MediumPurple;"> Diagnostics <span>

In [52]:
# Assign the residuals to a variable
residuals = linear_model.resid # The residuals

In [53]:
# Plot the residuals
go.Figure(data=go.Scatter(x=independent, y=residuals,
    mode='markers',
    name='Residuals',
    marker=dict(size=12))).update_layout(title='Residual plot',
        yaxis=dict(title='Residuals'),
        xaxis=dict(title='Independent variable')).add_trace(go.Scatter(
            x=[np.min(independent), np.max(independent)],
            y=[0, 0],
            name='Zero line',
            mode='lines'
        )).update_layout(
            width=700
        )

In [54]:
stats.pearsonr(
    independent,
    residuals
)

PearsonRResult(statistic=np.float64(-5.49368978328182e-16), pvalue=np.float64(0.9999999999999973))

### <span style="color: pink;"> Multiple Linear Regression <span>

In [67]:
np.random.seed(7) # For reproducible results


# Generating numpy arrays with random values
var1 = np.random.randint(low=100, high=200, size=100) / 10
var2 = np.random.randn(100)
dependent = var1 + var2 + (np.random.randn(100) * 10)

# Add the arrays to a DataFrame object
df = DataFrame(
    {
        'Variable1':var1,
        'Variable2':var2,
        'Dependent':dependent
    }
)
df[:10]

Variable1  Variable2  Dependent
0       14.7   0.767522  21.077552
1       16.8   1.993467   7.551747
2       12.5   1.987638  34.172534
3       16.7  -0.650286  17.067763
4       18.3   0.967063  33.966517
5       12.3   0.461899  16.757746
6       19.2  -0.564692  23.405064
7       15.7   0.039937  14.627540
8       11.4   1.656424  27.713588
9       12.3  -0.886184  10.201558

In [56]:
go.Figure(
    data=go.Scatter(
        x=df.Variable1,
        y=df.Variable2,
        mode='markers',
        marker=dict(
            size=16,
            color=df.Dependent,
            colorscale='Viridis',
            showscale=True
        )
    )
).update_layout(title='Scatter plot of independent variables and heatmap as dependent variable',
                width=700)

In [68]:
px.scatter_matrix(
    df,
    title='Scatter plot matrix'
)

In [69]:
# Target vector and design matrix
y, X = dmatrices(
    'Dependent ~ Variable1 + Variable2',
    data = df
)

In [70]:
X[:5]

array([[ 1.        , 14.7       ,  0.76752164],
       [ 1.        , 16.8       ,  1.99346654],
       [ 1.        , 12.5       ,  1.98763755],
       [ 1.        , 16.7       , -0.65028648],
       [ 1.        , 18.3       ,  0.96706308]])

In [71]:
# Create the model
multi_lin_model = sm.OLS(y, X).fit()

In [72]:
# Print the summary results
multi_lin_model.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                 Results: Ordinary least squares
=================================================================
Model:              OLS              Adj. R-squared:     0.090   
Dependent Variable: Dependent        AIC:                744.9274
Date:               2025-04-22 10:32 BIC:                752.7429
No. Observations:   100              Log-Likelihood:     -369.46 
Df Model:           2                F-statistic:        5.919   
Df Residuals:       97               Prob (F-statistic): 0.00375 
R-squared:          0.109            Scale:              97.696  
------------------------------------------------------------------
               Coef.   Std.Err.     t     P>|t|    [0.025   0.975]
------------------------------------------------------------------
Intercept     -1.0602    5.2183  -0.2032  0.8394  -11.4171  9.2966
Variable1      1.1487    0.3429   3.3497  0.0012    0.4681  1.8292
Variable2      0.6303    0.8886   0.7094  0.4798   -1.1333  2.3939
-----------------------------------------------------------------
Omnibus:              0.907        Durbin-Watson:           1.801
Prob(Omnibus):        0.635        Jarque-Bera (JB):        0.894
Skew:                 0.019        Prob(JB):                0.639
Kurtosis:             2.538        Condition No.:           81   
=================================================================
Notes:
[1] Standard Errors assume that the covariance matrix of the
errors is correctly specified.
"""

In [62]:
# Variance in mean model and working model
var_mean_model = np.var(df.Dependent)
var_best_model = np.var(multi_lin_model.resid)

In [73]:
(var_mean_model - var_best_model) / var_mean_model

np.float64(0.02265232590878605)

In [74]:
p_best = 3
p_mean = 1
n = len(df.Dependent)

In [75]:
# F statistic
F = ((var_mean_model - var_best_model) / (p_best - p_mean)) / ((var_best_model) / (n - p_best))
F

np.float64(1.1241013159392752)

In [76]:
# The p value
1 - stats.f.cdf(F, p_best - p_mean, n - p_best)

np.float64(0.329139922335588)

## <span style="color: MediumPurple;"> No need todo the quiz questions today :) <span>